### ISSUE TITLE
(yarn) Dependencies fail to install using commands from The Graph Studio section

### ISSUE THREAD

**Issue by DorianDaSilva** [graphprotocol/graph-tooling#997] opened 2022-11-16 16:15 UTC
@schmidsi 
Thank you for the reply on issue: https://github.com/graphprotocol/graph-cli/issues/992 
This issue is unrelated to issue: https://github.com/graphprotocol/graph-cli/issues/995

Unfortunately the fix did not solve my issue. I run the commands to create a subgraph as instructed in graph studio but the issue persists. I did confirm the CLI version installed is 0.36.1 as requested.

I will be sharing the terminal output below as it could provide to be helpful identifying the root cause of the problem. 
I hope this helps sorting it out! 

**Install graph-cli**
![image](https://user-images.githubusercontent.com/80294826/202231715-41b2620e-b9d9-426c-8a10-046d21ffd580.png)

**Init subgraph**
![image](https://user-images.githubusercontent.com/80294826/202232035-6bfd39a6-f0c7-4d20-95d4-e27ad7548ed2.png)
![image](https://user-images.githubusercontent.com/80294826/202232199-dbfdb1d0-54d5-4e6c-8f19-da1a2a787def.png)
![image](https://user-images.githubusercontent.com/80294826/202232752-d7c9828c-c193-4bfc-b15c-d98ab3fc6dba.png)
![image](https://user-images.githubusercontent.com/80294826/202233009-9af2f4d9-6fd2-4c85-8e4e-70a83f06089f.png)
![image](https://user-images.githubusercontent.com/80294826/202233157-5262c2c6-9bd3-451b-8eac-3f0185624c11.png)
![image](https://user-images.githubusercontent.com/80294826/202233314-7e498de7-6e7e-4ee1-97f3-f75570129a55.png)

Thank you!

**Comment by azf20** [comment] 2023-03-08 21:19
Hi @DorianDaSilva I think this is the same as the issue being investigated here https://github.com/graphprotocol/graph-tooling/issues/1052, closing here but please re-open if you think it's a different root cause

**Closed by azf20** 2023-03-08 21:19 UTC
Labels: area/cli
